export const NETWORK_ERROR =500
export const NOT_FOUND_ERROR =404
export const FORBIDDEN_ERROR =403
export const UNHAUTORIZED_ERROR =401
export const TIMEOUT_ERROR =408
export const BAD_REQUEST_ERROR =400
export const RESSOURCES_FETCHED_SUCCESS = 200
export const RESSOURCES_CREATED_SUCCESS = 201